=== hotphongxukhung/prx301/CrawlingTools/src/phongnd/dtd/phone.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT phone (name, screen, screen-resolution, screen-size, camera-front, camera-back, operating-system, cpu, gpu, ram, rom, battery)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT screen-resolution (#PCDATA)>
<!ELEMENT screen-size (#PCDATA)>
<!ELEMENT camera-front (#PCDATA)>
<!ELEMENT camera-back (#PCDATA)>
<!ELEMENT operating-system (#PCDATA)>
<!ELEMENT cpu (#PCDATA)>
<!ELEMENT gpu (#PCDATA)>
<!ELEMENT ram (#PCDATA)>
<!ELEMENT rom (#PCDATA)>
<!ELEMENT battery (#PCDATA)>

=== hotphongxukhung/prx301/CrawlingTools/src/phongnd/xsl/phonevalid.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE phone SYSTEM "D:\New folder\PRX301\Exercise\FP\CrawlingTools\src\phongnd\dtd\phone.dtd"><phone><name>
LG G6 Quốc Tế Mỹ Cũ</name><screen>
IPS LCD</screen><screen-resolution>
2K+ (1440 x 2880 Pixels)</screen-resolution><screen-size>
5.7"</screen-size><camera-front>
Chính 13 MP &amp;amp; Phụ 13 MP</camera-front><camera-back>
5 MP</camera-back><operating-system>
Android 7.0 (Nougat)</operating-system><cpu>
Qualcomm Snapdragon 821</cpu><gpu>
Adreno 530</gpu><ram>
4 GB</ram><rom>
32GB</rom><battery>
3300 mAh</battery></phone>
